name: Compile and Release v2
on:
  workflow_dispatch:
  push:
    tags:
      - "v*"
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install dependencies
        run: npm i

      - name: Package into node binary
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
              ./node_modules/.bin/pkg . -t latest-linux-x64 --options no-warnings -o build/WA2DC-$RUNNER_OS
          elif [ "$RUNNER_OS" == "macOS" ]; then
              ./node_modules/.bin/pkg . -t latest-macos-x64 --options no-warnings -o build/WA2DC-$RUNNER_OS
          elif [ "$RUNNER_OS" == "Windows" ]; then
              ./node_modules/.bin/pkg . -t latest-win-x64 --options no-warnings -o build/WA2DC-$RUNNER_OS
          else
              echo "$RUNNER_OS not supported"
              exit 1
          fi
        shell: bash

      - name: Create Signature
        uses: FKLC/sign-files-action@v1.0.0
        with:
          privateKey: ${{ secrets.PK }}
          passphrase: ${{ secrets.PK_PASSPHRASE }}
          outputFolder: build/
          files: |
            build/**

      - name: Upload binary and signature as artifact
        uses: actions/upload-artifact@v3
        with:
          name: WA2DC-${{ matrix.os }}
          path: build/**

  release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name: Download complied binaries and signatures
        uses: actions/download-artifact@v3
        with:
          path: builds

      - name: Make a draft release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: builds/**
